### PR TITLE
Add NixOS support

### PR DESCRIPTION
**Pull request by erikreinert**
## Changes

- we have shown how we install on `nix-darwin` now we want to show the same process for `NixOS`

## Things to do

- [x] make distro dynamic so user only needs to provide archetype (ie. user provides "x86_64-linux" and it can generate systems for both `darwinConfigurations` and `nixosConfigurations`

### CODE REVIEW

**Comment by daVinci13** [comment]
`#!/bin/bash

architecture=$(uname -m)

case $architecture in
    x86_64)
        echo "64-bit"
        ;;
    i*86)
        echo "32-bit"
        ;;
    arm*)
        echo "ARM"
        ;;
    *)
        echo "Unknown architecture: $architecture"
        ;;
esac

read -p "Enter your username: " username
echo "Your username is: $username"
`

**Comment by countoren** [comment]
```nix
packages.${system}.user =  pkgs.writeShellScript "changeUser" ''
read -p "Enter your username: " username
echo "Your username is: $username"
sed ....username
'';
packages.${system}.default = pkgs.writeShelScriptBin "install" ''
 ${self.packages.${system}.user} && \
 uname thing ..
''
```
something along this line.

**Comment by eth3lbert** [comment]
You could also write a function which accept some args like `system`
```nix
      mkDarwinConfig = system: inputs.darwin.lib.darwinSystem {
        # system: supports only 1 system
        inherit system;
        # modules: allows for reusable code
        modules = [
        {
          services.nix-daemon.enable = true;
          users.users.${username}.home = "/Users/${username}";
        }
        system-config

          inputs.home-manager.darwinModules.home-manager
          {
            # add home-manager settings here
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users." ${username}" = home-manager-config;
          }
          # add more nix modules here
        ];
      };
```

**Comment by erikreinert** [comment]
We wanted to try and make the `system` value be as easy to setup as possible without making it too "magical". Before you'd need both the `username` and `system` set before you could switch to a profile. Now you set the `username` only in `flake.nix` and then use the desired profile for your platform such as below:

```bash
darwin-rebuild check --flake ".#darwin-x86_64"
nixos-rebuild check --flake ".#nixos-x86_64"
```

**Pull request merged**
